### ISSUE TITLE
(2) Typos-Quick Fixes "Numbers" &   "a" to "an"

### ISSUE THREAD

**Issue by ccklight** [learn-co-curriculum/git-version-control-git-basics#3]
Hi- quick and easy fixes.  

1 Last line "numbers" 
************************
We can see that Git has created a new version of our repo, represented by the SHA e55477d. SHAs are the identification system that git uses to keep track of versions; they're long complex numberes and letters that are unlikely to be duplicated.
***********************
2. Below, CHANGE 'a' explanatory message" to 'an'
***********************
Once your changes have been added, or "staged," use git commit -m to commit them with a explanatory message. You can shorten the add + commit process, provided that all the files are being tracked by using git commit -am "A Message".

**Comment by Sdcrouse** [comment]
I have sent them a pull request for that here: https://github.com/learn-co-students/git-version-control-git-basics-v-000/pull/2

Sdcrouse

**Comment by sgharms** [comment]
We got these fixed! Thanks
