### ISSUE TITLE
Quick Fix: Change "with out'  to  "with our" 

### ISSUE THREAD

**Issue by ccklight** [learn-co-curriculum/git-version-control-git-basics#4]
Last line. 
***************
Create a Commit and Apply a Commit Message with git commit
Remember: git add got our changes to the repository ready in the previous step. Those changes are the ones that will be "captured" with out commit.

**Comment by Sdcrouse** [comment]
It looks like someone make a pull request for that here: https://github.com/learn-co-students/git-version-control-git-basics-v-000/pull/1

Sdcrouse

**Comment by sgharms** [comment]
All set!
