### ISSUE TITLE
Output of "git status" is different in the terminal than in the lesson.

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/git-version-control-git-basics#5]
Hi. I've been following along with this lesson in the Sandbox. In the "Check the Status of a Repository with git status" section, it says that entering `git status` should return
```
On branch master
 
No commits yet
 
nothing to commit (create/copy files and use "git add" to track)
```
The first and last lines are the same for me, but instead of "No commits yet", my terminal says "Initial commit". The same is true further down in the lesson, when I enter `git status` after making a README.md file, and again after entering `git add README.md.`

I don't know if this is the same result for other people, so I have chosen not to submit a pull request for this issue as of yet. I'll be more than happy to make one, with your permission.

Thanks for checking this out!

Sdcrouse

**Comment by drakeltheryuujin** [comment]
Hi @Sdcrouse,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

Make sure that you are in a directory that isn't already initialized as a `git` repo. A new directory initialized for that first time shouldn't have pre-existing files or commits.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information, I'd be happy to take a second look!

As always, thanks for contributing! 💙
